name = "Spectestpack"
author = "KatTheFox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fde6a6252d3c62f53e79ec7fbf6cc766ca004831c5e170e60ba8fc46a7d0502"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
